configure (cosmetic): Adjust indent and add blank lines.
git-svn-id: svn://git.mplayerhq.hu/mplayer/trunk@36885 b3059339-0415-0410-9bf9-f77b7e298cf2

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7789,19 +7789,20 @@ if test "$_gui" = yes ; then
   # Required libraries
   test "$ffmpeg" != yes && die "The GUI requires FFmpeg."
   test "$ffmpeg_so" = yes || case "$libavdecoders" in
-      *PNG_DECODER*) ;;
-      *) die "The GUI requires libavcodec with PNG support (needs zlib)." ;;
+    *PNG_DECODER*) ;;
+    *) die "The GUI requires libavcodec with PNG support (needs zlib)." ;;
   esac
   test "$_freetype" = no && test "$_bitmap_font" = no &&
     die "The GUI requires either FreeType or bitmap font support."
-if ! win32 ; then
-  _gui_gtk=yes
-  test "$_x11" != yes && die "X11 support required for GUI compilation."
 
-  echocheck "XShape extension"
-  if test "$_xshape" = auto ; then
-    _xshape=no
-    cat > $TMPC << EOF
+  if ! win32 ; then
+    _gui_gtk=yes
+    test "$_x11" != yes && die "X11 support required for GUI compilation."
+
+    echocheck "XShape extension"
+    if test "$_xshape" = auto ; then
+      _xshape=no
+      cat > $TMPC << EOF
 #include <X11/Xlib.h>
 #include <X11/Xproto.h>
 #include <X11/Xutil.h>
@@ -7813,95 +7814,96 @@ int main(void) {
   int exitvar = 0;
   int eventbase, errorbase;
   if (getenv("DISPLAY"))
-    name=getenv("DISPLAY");
+      name=getenv("DISPLAY");
   wsDisplay=XOpenDisplay(name);
   if (!XShapeQueryExtension(wsDisplay, &eventbase, &errorbase))
-    exitvar=1;
+      exitvar=1;
   XCloseDisplay(wsDisplay);
   return exitvar;
 }
 EOF
-    cc_check -lXext && _xshape=yes
-  fi
-  if test "$_xshape" = yes ; then
-    def_xshape='#define CONFIG_XSHAPE 1'
-  else
-    die "The GUI requires the X11 extension XShape (which was not found)."
-  fi
-  echores "$_xshape"
+      cc_check -lXext && _xshape=yes
+    fi
+    if test "$_xshape" = yes ; then
+      def_xshape='#define CONFIG_XSHAPE 1'
+    else
+      die "The GUI requires the X11 extension XShape (which was not found)."
+    fi
+    echores "$_xshape"
 
-#Check for GTK
-if test "$_gtk1" = no ; then
-  #Check for GTK2 :
-  echocheck "GTK+ version"
+    # Check for GTK
+    if test "$_gtk1" = no ; then
+      # Check for GTK2 :
+      echocheck "GTK+ version"
 
-  if $_pkg_config gtk+-2.0 --exists ; then
-    _gtk=$($_pkg_config gtk+-2.0 --modversion 2>/dev/null)
-    extra_cflags="$extra_cflags $($_pkg_config gtk+-2.0 --cflags 2>/dev/null)"
-    libs_mplayer="$libs_mplayer $($_pkg_config gtk+-2.0 --libs 2>/dev/null)"
-    echores "$_gtk"
+      if $_pkg_config gtk+-2.0 --exists ; then
+        _gtk=$($_pkg_config gtk+-2.0 --modversion 2>/dev/null)
+        extra_cflags="$extra_cflags $($_pkg_config gtk+-2.0 --cflags 2>/dev/null)"
+        libs_mplayer="$libs_mplayer $($_pkg_config gtk+-2.0 --libs 2>/dev/null)"
+        echores "$_gtk"
 
-    # Check for GLIB2
-    echocheck "GLib version"
-    if $_pkg_config glib-2.0 --exists ; then
-      _glib=$($_pkg_config glib-2.0 --modversion 2>/dev/null)
-      libs_mplayer="$libs_mplayer $($_pkg_config glib-2.0 --libs 2>/dev/null)"
-      echores "$_glib"
+        # Check for GLIB2
+        echocheck "GLib version"
+        if $_pkg_config glib-2.0 --exists ; then
+          _glib=$($_pkg_config glib-2.0 --modversion 2>/dev/null)
+          libs_mplayer="$libs_mplayer $($_pkg_config glib-2.0 --libs 2>/dev/null)"
+          echores "$_glib"
+
+          def_gui='#define CONFIG_GUI 1'
+          def_gtk2='#define CONFIG_GTK2 1'
+        else
+          _gtk1=yes
+          echores "GLib 2 devel packages were not found, trying GTK+ 1.2"
+        fi
+      else
+        echores "GTK+ 2 devel packages were not found, trying GTK+ 1.2"
+        _gtk1=yes
+      fi
+    fi
+
+    if test "$_gtk1" = yes ; then
+      # Check for old GTK (1.2.x)
+      echocheck "GTK+ version"
+
+      if test -z "$_gtkconfig" ; then
+        if ( gtk-config --version ) >/dev/null 2>&1 ; then
+          _gtkconfig="gtk-config"
+        elif ( gtk12-config --version ) >/dev/null 2>&1 ; then
+          _gtkconfig="gtk12-config"
+        else
+          die "The GUI requires GTK+ devel packages (which were not found)."
+        fi
+      fi
+      _gtk=$($_gtkconfig --version 2>&1)
+      extra_cflags="$extra_cflags $($_gtkconfig --cflags 2>&1)"
+      libs_mplayer="$libs_mplayer $($_gtkconfig --libs 2>&1)"
+      echores "$_gtk (using $_gtkconfig)"
+
+      # Check for GLIB
+      echocheck "GLib version"
+      if test -z "$_glibconfig" ; then
+        if ( glib-config --version ) >/dev/null 2>&1 ; then
+          _glibconfig="glib-config"
+        elif ( glib12-config --version ) >/dev/null 2>&1 ; then
+          _glibconfig="glib12-config"
+        else
+          die "The GUI requires GLib devel packages (which were not found)"
+        fi
+      fi
+      _glib=$($_glibconfig --version 2>&1)
+      libs_mplayer="$libs_mplayer $($_glibconfig --libs 2>&1)"
+      echores "$_glib (using $_glibconfig)"
 
       def_gui='#define CONFIG_GUI 1'
-      def_gtk2='#define CONFIG_GTK2 1'
-    else
-      _gtk1=yes
-      echores "GLib 2 devel packages were not found, trying GTK+ 1.2"
+      def_gtk2='#undef CONFIG_GTK2'
     fi
-  else
-    echores "GTK+ 2 devel packages were not found, trying GTK+ 1.2"
-    _gtk1=yes
-  fi
-fi
 
-if test "$_gtk1" = yes ; then
-  # Check for old GTK (1.2.x)
-  echocheck "GTK+ version"
-  if test -z "$_gtkconfig" ; then
-    if ( gtk-config --version ) >/dev/null 2>&1 ; then
-      _gtkconfig="gtk-config"
-    elif ( gtk12-config --version ) >/dev/null 2>&1 ; then
-      _gtkconfig="gtk12-config"
-    else
-      die "The GUI requires GTK+ devel packages (which were not found)."
-    fi
-  fi
-  _gtk=$($_gtkconfig --version 2>&1)
-  extra_cflags="$extra_cflags $($_gtkconfig --cflags 2>&1)"
-  libs_mplayer="$libs_mplayer $($_gtkconfig --libs 2>&1)"
-  echores "$_gtk (using $_gtkconfig)"
-
-  # Check for GLIB
-  echocheck "GLib version"
-  if test -z "$_glibconfig" ; then
-    if ( glib-config --version ) >/dev/null 2>&1 ; then
-      _glibconfig="glib-config"
-    elif ( glib12-config --version ) >/dev/null 2>&1 ; then
-      _glibconfig="glib12-config"
-    else
-      die "The GUI requires GLib devel packages (which were not found)"
-    fi
-  fi
-  _glib=$($_glibconfig --version 2>&1)
-  libs_mplayer="$libs_mplayer $($_glibconfig --libs 2>&1)"
-  echores "$_glib (using $_glibconfig)"
-
-  def_gui='#define CONFIG_GUI 1'
-  def_gtk2='#undef CONFIG_GTK2'
-fi
-
-else #if ! win32
-  _gui_win32=yes
-  libs_mplayer="$libs_mplayer -lcomdlg32 -lcomctl32 -lshell32 -lkernel32"
-  def_gui='#define CONFIG_GUI 1'
-  def_gtk2='#undef CONFIG_GTK2'
-fi #if ! win32
+  else #if ! win32
+    _gui_win32=yes
+    libs_mplayer="$libs_mplayer -lcomdlg32 -lcomctl32 -lshell32 -lkernel32"
+    def_gui='#define CONFIG_GUI 1'
+    def_gtk2='#undef CONFIG_GTK2'
+  fi #if ! win32
 
 else #if test "$_gui"
   def_gui='#undef CONFIG_GUI'
