Avoid link issues for MinGW.
-fno-asynchronous-unwind-tables seems potentially buggy.

git-svn-id: svn://git.mplayerhq.hu/mplayer/trunk@37832 b3059339-0415-0410-9bf9-f77b7e298cf2

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2868,7 +2868,12 @@ fi
 # This provides significant size savings on gcc.
 # I will cause worse backtraces when debug info is missing though,
 # but having non-stripable debug info is not really a desirable feature.
+# Unfortunately MinGW toolchains seem to have a bug where it tries
+# to use SjLj exception handling even if not supported by the toolchain,
+# causing linking failure for C++ code like demux_rtp.cpp
+if ! mingw32 ; then
 cflag_check -fno-asynchronous-unwind-tables && CFLAGS="$CFLAGS -fno-asynchronous-unwind-tables"
+fi
 cflag_check -mno-omit-leaf-frame-pointer && cflags_no_omit_leaf_frame_pointer="-mno-omit-leaf-frame-pointer"
 cflag_check -MMD -MP && DEPFLAGS="-MMD -MP"
 
